### ISSUE TITLE
when add --vnet-subnet-id paramter, the karpanter not

### ISSUE THREAD

**Issue by ottodeng** [Azure/karpenter-provider-azure#269] opened 2024-04-16 07:55 UTC
### Version

az aks create --name pix-nap-sg03 -l southeastasia \
--resource-group pix-nap \
--node-provisioning-mode Auto \
--network-plugin-mode overlay \
--network-dataplane cilium \
--max-pods 110 --node-count 3 \
--service-cidr 10.97.96.0/20 --dns-service-ip 10.97.96.10 \
--network-plugin azure --enable-managed-identity \
--node-osdisk-size 512 --node-vm-size Standard_D2s_v4 \
--vnet-subnet-id /subscriptions/2a5e7fa2-d528-4c66-9e6a-3a3a0f290e98/resourcegroups/pix-nap/providers/Microsoft.Network/virtualNetworks/aks-nap-vnet-junfeng/subnets/aks \
--ssh-key-value ~/.ssh/id_rsa.pub \
--tier premium --k8s-support-plan AKSLongTermSupport --kubernetes-version 1.27 --yes

### Expected Behavior

nodeclaim will created success.

### Actual Behavior

no any nodeclaim create.

(base) ottodeng@Otto-MacBook-Pro-M2.local:/Users/ottodeng/aks $ kubectl get nodeclaims.karpenter.sh 
No resources found
(base) ottodeng@Otto-MacBook-Pro-M2.local:/Users/ottodeng/aks $ kubectl get events -A --field-selector source=karpenter   
No resources found
(base) ottodeng@Otto-MacBook-Pro-M2.local:/Users/ottodeng/aks $ 

(base) ottodeng@Otto-MacBook-Pro-M2.local:/Users/ottodeng/aks $ kubectl get pod
NAME                  READY   STATUS    RESTARTS   AGE
pix-88d6475c8-kt8gb   0/1     Pending   0          7m54s
(base) ottodeng@Otto-MacBook-Pro-M2.local:/Users/ottodeng/aks $ kubectl describe pod pix-88d6475c8-kt8gb 
Name:             pix-88d6475c8-kt8gb
Namespace:        default
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app=samples-tf-mnist-demo
                  pod-template-hash=88d6475c8
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/pix-88d6475c8
Containers:
  samples-tf-mnist-demo:
    Image:      mcr.microsoft.com/azuredocs/samples-tf-mnist-demo:gpu
    Port:       <none>
    Host Port:  <none>
    Args:
      --max_steps
      50000
    Limits:
      nvidia.com/gpu:  1
    Requests:
      nvidia.com/gpu:  1
    Environment:       <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-f7tj8 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-f7tj8:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                             nvidia.com/gpu:NoSchedule op=Exists
                             pool-type=t4:NoSchedule
                             sku=gpu:NoSchedule
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  2m37s (x4 over 8m7s)  default-scheduler  0/3 nodes are available: 3 Insufficient nvidia.com/gpu. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod..
(base) ottodeng@Otto-MacBook-Pro-M2.local:/Users/ottodeng/aks $ 

### Steps to Reproduce the Problem

az aks create --name pix-nap-sg03 -l southeastasia \
--resource-group pix-nap \
--node-provisioning-mode Auto \
--network-plugin-mode overlay \
--network-dataplane cilium \
--max-pods 110 --node-count 3 \
--service-cidr 10.97.96.0/20 --dns-service-ip 10.97.96.10 \
--network-plugin azure --enable-managed-identity \
--node-osdisk-size 512 --node-vm-size Standard_D2s_v4 \
--vnet-subnet-id /subscriptions/2a5e7fa2-d528-4c66-9e6a-3a3a0f290e98/resourcegroups/pix-nap/providers/Microsoft.Network/virtualNetworks/aks-nap-vnet-junfeng/subnets/aks \
--ssh-key-value ~/.ssh/id_rsa.pub \
--tier premium --k8s-support-plan AKSLongTermSupport --kubernetes-version 1.27 --yes

### Resource Specs and Logs

no any karpenter log.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment] 2024-04-16 16:27
https://github.com/Azure/karpenter-provider-azure/issues/199

**Comment by Bryce-Soghigian** [comment] 2024-04-16 16:27
We are in the process of preparing an image for "--vnet-subnet-id" support as we speak.

**Comment by Bryce-Soghigian** [comment] 2024-04-16 16:29
Duplicate of #199, we are in the process of rolling out this support right now for node auto provisioning. Self-hosted karpenter has support for this change already. Thank you for your patience!

**Closed by Bryce-Soghigian** 2024-04-16 16:29 UTC

**Comment by Bryce-Soghigian** [comment] 2024-04-16 16:31
https://github.com/Azure/karpenter-provider-azure/pull/238 is the PR that added support.
