### ISSUE TITLE
[BUG] Karpenter does not clean up network interface upon node deletion causing IP exhaustion in subnet

### ISSUE THREAD

**Issue by mdfaizsiddiqui** [Azure/karpenter-provider-azure#543] opened 2024-10-25 18:29 UTC
### Version

__Karpenter Version:__ v0.6.0

__Kubernetes Version:__ v1.30.2

### Expected Behavior

When a node is deleted, all associated resources—such as the VM, disk, and network interface created for each node claim—should be removed.

![Image](https://github.com/user-attachments/assets/b689eac2-074b-4d9a-9f49-3ec3f4cf72e9)

### Actual Behavior

When Karpenter deletes a node, it does not clean up the associated network interface in the subnet. As a result, the IP addresses assigned to these interfaces are not released back into the subnet’s pool, leading to IP exhaustion over time. This issue can prevent new nodes from being provisioned and affect overall cluster scalability.

For a deleted node/nodeclaim, I see that network interface still exists and I had to remove residual network interfaces to free up IPs.

![Image](https://github.com/user-attachments/assets/2ad7bb52-8cca-4806-ae36-8daea3810bcf)

### Steps to Reproduce the Problem

1. Provision a node with Karpenter in a subnet.
2. Delete the node via karpenter and observe the associated network interface remains attached, consuming an IP address in the subnet.
3. Repeat until the subnet runs out of available IPs.

### Resource Specs and Logs

.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment] 2024-10-28 17:18
Duplicate of https://github.com/Azure/karpenter-provider-azure/issues/92

**Closed by tallaxes** 2024-10-28 17:18 UTC
Labels: kind/bug, triage/duplicate, area/networking
