### ISSUE TITLE
Support custom DNS service

### ISSUE THREAD

**Issue by tangyouzzz** [Azure/karpenter-provider-azure#561] opened 2024-11-04 13:29 UTC
### Tell us about your request

CSE does not seem to support custom DNS services. I noticed that clusterDNS in nodeclass has also been removed. I want to know if there is a solution to this

https://learn.microsoft.com/en-us/azure/aks/custom-node-configuration%20?tabs=linux-node-pools#linux-kubelet-custom-configuration

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

The DNS of the pod on the new node is using the default DNS on the node, which will cause the pod to be unable to resolve SVC

### Are you currently working around this issue?

I am currently using aksscriptless on the latest branch and added '-- cluster dns' to kubelet during aksbootstrap. I personally think that since we have separated bootstrappingclient and aksscriptless, should aksscripeless also support more complete custom kubelets? 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tallaxes** [comment] 2024-11-06 01:20
Duplicate of https://github.com/Azure/karpenter-provider-azure/issues/335

Custom DNS will be natively supported in NAP (bootstrappingclient), with possible support in self-hosted (aksscripeless) later.

**Closed by tallaxes** 2024-11-06 01:20 UTC
